import { NextResponse } from 'next/server'
import { withAuth } from '@/lib/auth'
import { UserRole, AuditReportStatus } from '@prisma/client'
import { prisma } from '@/lib/prisma'
import { createClient } from '@supabase/supabase-js'
import { renderToBuffer, Document, Page, Text, View } from '@react-pdf/renderer'
import type { ReportContentJson, ReportOptions } from '@/lib/llm/types'
import { DEFAULT_REPORT_OPTIONS } from '@/lib/llm/types'
import { buildPdfTheme } from '@/lib/pdf-theme'
import React from 'react'

const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
)

function ReportDocument({
    report,
    content,
    options,
}: {
    report: any
    content: ReportContentJson
    options: ReportOptions
}) {
    const { styles } = buildPdfTheme(options)

    return React.createElement(
        Document, null,
        React.createElement(Page, { size: 'A4', style: styles.page },
            // AI banner
            React.createElement(View, { style: styles.aiBanner },
                React.createElement(Text, null,
                    '⚠️ AI-GENERATED DRAFT — Reviewed and approved by a human auditor.'
                )
            ),
            // Title block
            React.createElement(View, null,
                React.createElement(Text, { style: styles.title },
                    `${report.audit?.regulation?.replace(/_/g, ' ')} Certification Audit Report`
                ),
                React.createElement(Text, { style: styles.subtitle },
                    `${report.audit?.company?.name} · Version ${report.version} · ${new Date(report.generatedAt).toLocaleDateString()}`
                ),
            ),
            // Executive Summary
            React.createElement(View, null,
                React.createElement(Text, { style: styles.sectionHeader }, 'Executive Summary'),
                React.createElement(Text, { style: styles.body }, content.executiveSummary)
            ),
            // Findings by pillar
            ...(content.findingsByPillar ?? []).flatMap(pillar => [
                React.createElement(Text, { key: `ph-${pillar.pillar}`, style: styles.pillarHeader }, pillar.pillar),
                ...(pillar.items ?? []).map(item =>
                    React.createElement(View, { key: item.requirementCode, style: styles.findingRow },
                        React.createElement(Text, null,
                            React.createElement(Text, { style: styles.findingCode }, `[${item.requirementCode}] `),
                            `${item.requirementName}: ${item.summary} (${item.findingType})`
                        )
                    )
                ),
            ]),
            // Recommendations
            React.createElement(View, null,
                React.createElement(Text, { style: styles.sectionHeader }, 'Recommendations'),
                ...(content.recommendations ?? []).map((r: string, i: number) =>
                    React.createElement(Text, { key: i, style: styles.bullet }, `• ${r}`)
                )
            ),
            // Conclusion
            React.createElement(View, null,
                React.createElement(Text, { style: styles.sectionHeader }, 'Conclusion'),
                React.createElement(Text, { style: styles.body }, content.conclusion)
            ),
            // Footer
            React.createElement(Text, { style: styles.footer },
                `Generated by GreenTrace · ${new Date().toISOString()}`
            )
        )
    )
}

export const POST = withAuth(
    [UserRole.AUDITOR, UserRole.SUPER_ADMIN],
    async (_req: Request, context: any) => {
        const { id } = context.params

        const report = await prisma.auditReport.findUnique({
            where: { id },
            include: {
                audit: { include: { company: true } },
            },
        })
        if (!report) return NextResponse.json({ error: 'Not found' }, { status: 404 })
        if (report.status !== AuditReportStatus.FINAL) {
            return NextResponse.json({ error: 'Only FINAL reports can be exported to PDF.' }, { status: 400 })
        }

        const content = report.contentJson as unknown as ReportContentJson
        // reportOptions is a Json? scalar — cast via unknown to avoid Prisma include type narrowing
        const options = ((report as unknown as Record<string, unknown>).reportOptions as ReportOptions | null) ?? DEFAULT_REPORT_OPTIONS

        const docElement = React.createElement(ReportDocument, { report, content, options }) as unknown as React.ReactElement<import('@react-pdf/renderer').DocumentProps>
        const pdfBuffer  = await renderToBuffer(docElement)

        const storagePath = `audit-reports/${report.auditId}/${id}.pdf`
        const { error: uploadError } = await supabase.storage
            .from('greentrace-docs')
            .upload(storagePath, pdfBuffer, { contentType: 'application/pdf', upsert: true })

        if (uploadError) {
            return NextResponse.json({ error: `Storage upload failed: ${uploadError.message}` }, { status: 500 })
        }

        const { data: signedUrlData } = await supabase.storage
            .from('greentrace-docs')
            .createSignedUrl(storagePath, 3600)

        await prisma.auditReport.update({ where: { id }, data: { pdfPath: storagePath } })

        return NextResponse.json({ data: { signedUrl: signedUrlData?.signedUrl, pdfPath: storagePath } })
    }
)
